### ISSUE TITLE
训练数据集问题

### ISSUE THREAD

**Issue by yjg123456** [Lvfeifan/MBLLEN#16]
作者你好，我训练自己的数据集的时候出现了以下的问题
Epoch 1/200
LR = 0.001
Traceback (most recent call last):
  File "train.py", line 196, in <module>
    callbacks=[tbCallBack, show_history, change_lr, nanstop, reducelearate])
  File "/home/gfzx/anaconda3/envs/yjgMBLLEN/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper    return func(*args, **kwargs)
  File "/home/gfzx/anaconda3/envs/yjgMBLLEN/lib/python3.6/site-packages/keras/engine/training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/gfzx/anaconda3/envs/yjgMBLLEN/lib/python3.6/site-packages/keras/engine/training_generator.py", line 181, in fit_generator
    generator_output = next(output_generator)
  File "/home/gfzx/anaconda3/envs/yjgMBLLEN/lib/python3.6/site-packages/keras/utils/data_utils.py", line 709, in get
    six.reraise(*sys.exc_info())
  File "/home/gfzx/anaconda3/envs/yjgMBLLEN/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/gfzx/anaconda3/envs/yjgMBLLEN/lib/python3.6/site-packages/keras/utils/data_utils.py", line 685, in get
    inputs = self.queue.get(block=True).get()
  File "/home/gfzx/anaconda3/envs/yjgMBLLEN/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/home/gfzx/anaconda3/envs/yjgMBLLEN/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/gfzx/anaconda3/envs/yjgMBLLEN/lib/python3.6/site-packages/keras/utils/data_utils.py", line 626, in next_sample
    return six.next(_SHARED_SEQUENCES[uid])
  File "/home/gfzx/yjg/MBLLEN-master/main/data_load.py", line 40, in load_data
    img_A = self.imread_color(path_A)
  File "/home/gfzx/yjg/MBLLEN-master/main/data_load.py", line 14, in imread_color
    img = cv.imread(path, cv.IMREAD_COLOR | cv.IMREAD_ANYDEPTH)/255.
TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'
请问可以帮忙指点以下吗?

**Comment by yu-li** [comment]
http://www.phi-ai.org/project/AgLLNet/default.htm check our project page for training data
