### ISSUE TITLE
跑通代码？

### ISSUE THREAD

**Issue by 123Wynne** [Lvfeifan/MBLLEN#26]
是否有人跑通了这个代码？希望各位大佬能帮帮忙，可能是由于我的版本问题一直在报错，无法跑通模型，报错情况如下：
Using TensorFlow backend.
Traceback (most recent call last):
  File "D:\Literature\Code\MBLLEN\MBLLEN\main\test.py", line 31, in <module>
    mbllen = Network.build_mbllen((None, None, 3))
  File "D:\Literature\Code\MBLLEN\MBLLEN\main\Network.py", line 24, in build_mbllen
    if self.bias:
  File "E:\Python\anaconde1\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py", line 498, in __bool__
    return bool(self.read_value())
  File "E:\Python\anaconde1\lib\site-packages\tensorflow\python\framework\ops.py", line 900, in __bool__
    self._disallow_bool_casting()
  File "E:\Python\anaconde1\lib\site-packages\tensorflow\python\framework\ops.py", line 507, in _disallow_bool_casting
    self._disallow_in_graph_mode("using a `tf.Tensor` as a Python `bool`")
  File "E:\Python\anaconde1\lib\site-packages\tensorflow\python\framework\ops.py", line 494, in _disallow_in_graph_mode
    raise errors.OperatorNotAllowedInGraphError(
tensorflow.python.framework.errors_impl.OperatorNotAllowedInGraphError: using a `tf.Tensor` as a Python `bool` is not allowed in Graph execution. Use Eager execution or decorate this function with @tf.function.

**Comment by rxqH** [comment]
tensorflow 1.9  py3.6   kera 2.2

**Comment by 123Wynne** [comment]
> 您好，您是否跑通了？是否可以加一个联系方式呢？

**Comment by rxqH** [comment]
q  1377854874

**Comment by 123Wynne** [comment]
> q 137785487
我昨晚已经加您了，您有时间还要同意一下。

**Comment by rxqH** [comment]
sorry 我留错了  应该是q 1377854974

**Comment by lemon2313** [comment]
训练集要训练16920张图片吗，可我每次都是训练前16张
